# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Klega' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Klega

  target 'Klega-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  end

  target 'KlegaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Klega-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Klega-tvOS

  target 'Klega-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
